#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${DWH_USER} WITH PASSWORD '${DWH_PASSWORD}';
    CREATE DATABASE ${DWH_DB} OWNER ${DWH_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${DWH_DB} TO ${DWH_USER};
EOSQL
